# Schema for the configuration files of the Server General module.
server_general.settings:
  type: config_object
  label: 'Server General settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
    name:
      type: 'label'
      label: 'Name'
    node:
      type: integer
      label: 'Node ID'
