<?php

/**
 * @file
 * Primary module hooks for Server General module.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_ENTITY_TYPE_presave() for node.
 *
 * Add the current date to the title of the node of the Article content type.
 */
function server_general_node_presave(NodeInterface $node) {
  if ($node->getType() === 'article') {
    $timestamp = \Drupal::service('datetime.time')->getRequestTime();
    $current_date = \Drupal::service('date.formatter')->format($timestamp, 'custom', 'd.m.Y');
    $title = t('@date - My first article', ['@date' => $current_date]);
    $node->set('title', $title);
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete() for node.
 *
 * Remove nid from the ThirdPartySetting of the Page content type.
 */
function server_general_node_delete(NodeInterface $node) {
  /** @var \Drupal\node\NodeTypeInterface $nodeType */
  $nodeType = \Drupal::service('entity_type.manager')->getStorage('node_type')->load('page');
  $nids = $nodeType->getThirdPartySetting('server_general', 'nids_with_attached_js');
  unset($nids[$node->id()]);
  $nodeType->setThirdPartySetting('server_general', 'nids_with_attached_js', $nids);
  $nodeType->save();
}
