<?php

/**
 * @file
 * Primary module hooks for Server General module.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_ENTITY_TYPE_presave() for node.
 *
 * Add the current date to the title of the node of the Article content type.
 */
function server_general_node_presave(NodeInterface $node) {
  if ($node->getType() === 'article') {
    $timestamp = \Drupal::service('datetime.time')->getRequestTime();
    $current_date = \Drupal::service('date.formatter')->format($timestamp, 'custom', 'd.m.Y');
    $title = t('@date - My first article', ['@date' => $current_date]);
    $node->set('title', $title);
  }
}

/**
 * Implements hook_preprocess_HOOK() for node templates.
 *
 * If the node was created by the CreateNodeController, then attach to it the
 * JS library for displaying the current date and time.
 */
function server_general_preprocess_node(&$variables) {
  $nid = $variables['node']->id();
  /** @var \Drupal\node\NodeTypeInterface $nodeType */
  $nodeType = \Drupal::service('entity_type.manager')->getStorage('node_type')->load('page');
  $nids = $nodeType->getThirdPartySetting('server_general', 'nids_with_attached_js', []);

  if (in_array($nid, $nids)) {
    $variables['#attached']['library'][] = 'server_general/display_current_date_and_time';
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete() for node.
 *
 * Remove nid from the ThirdPartySetting of the Page content type.
 */
function server_general_node_delete(NodeInterface $node) {
  /** @var \Drupal\node\NodeTypeInterface $nodeType */
  $nodeType = \Drupal::service('entity_type.manager')->getStorage('node_type')->load('page');
  $nids = $nodeType->getThirdPartySetting('server_general', 'nids_with_attached_js');
  unset($nids[$node->id()]);
  $nodeType->setThirdPartySetting('server_general', 'nids_with_attached_js', $nids);
  $nodeType->save();
}

/**
 * Implements template_preprocess_HOOK().
 *
 * Add site name to the variables. As we override the
 * 'block__system_branding_block' template, then 'site_name' variable already
 * exists. We add it here just for demo purposes.
 */
function template_preprocess_block__system_branding_block__server_general(&$variables) {
  $variables['my_site_name'] = \Drupal::config('system.site')->get('name');
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for block.
 */
function server_general_theme_suggestions_block_alter(array &$suggestions, array &$variables) {
  if ($variables['elements']['#plugin_id'] === 'system_branding_block') {
    $suggestions[] = 'block__system_branding_block__server_general';
  }
}

/**
 * Implements hook_theme().
 */
function server_general_theme($existing, $type, $theme, $path) {
  return [
    'block__system_branding_block__server_general' => [
      'base hook' => 'block',
    ],
  ];
}

/**
 * Implements hook_cron().
 *
 * Add to the queue articles that were edited 24 hours ago. Then the articles
 * will be re-saved in the "queue_uniqu/resave_articles" QueueWorker.
 */
function server_general_cron(): void {
  // Create the queue that only accepts unique items. To make this possible we
  // replaced the core QueueFactory class with the QueueFactory class provided
  // by the "Queue Unique" module. See the "server_general.services.yml" file.
  $queue = \Drupal::queue('queue_uniqu/resave_articles');
  $request_time = \Drupal::time()->getRequestTime();

  $nids = \Drupal::entityQuery('node')
    ->accessCheck(FALSE)
    ->condition('type', 'article')
    ->condition('changed', $request_time - (3600 * 24), '<')
    ->execute();

  foreach ($nids as $nid) {
    $queue->createItem(['nid' => intval($nid)]);
  }
}
