<?php

/**
 * @file
 * Primary module hooks for Server General module.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_ENTITY_TYPE_presave() for node.
 *
 * Add the current date to the title of the node of the Article content type.
 */
function server_general_node_presave(NodeInterface $node) {
  if ($node->getType() === 'article') {
    $timestamp = \Drupal::service('datetime.time')->getRequestTime();
    $current_date = \Drupal::service('date.formatter')->format($timestamp, 'custom', 'd.m.Y');
    $title = t('@date - My first article', ['@date' => $current_date]);
    $node->set('title', $title);
  }
}

/**
 * Implements hook_preprocess_HOOK() for node templates.
 *
 * If the node was created by the CreateNodeController, then attach to it the
 * JS library for displaying the current date and time.
 */
function server_general_preprocess_node(&$variables) {
  $nid = $variables['node']->id();
  /** @var \Drupal\node\NodeTypeInterface $nodeType */
  $nodeType = \Drupal::service('entity_type.manager')->getStorage('node_type')->load('page');
  $nids = $nodeType->getThirdPartySetting('server_general', 'nids_with_attached_js', []);

  if (in_array($nid, $nids)) {
    $variables['#attached']['library'][] = 'server_general/server_general.display_current_date_and_time';
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete() for node.
 *
 * Remove nid from the ThirdPartySetting of the Page content type.
 */
function server_general_node_delete(NodeInterface $node) {
  /** @var \Drupal\node\NodeTypeInterface $nodeType */
  $nodeType = \Drupal::service('entity_type.manager')->getStorage('node_type')->load('page');
  $nids = $nodeType->getThirdPartySetting('server_general', 'nids_with_attached_js');
  unset($nids[$node->id()]);
  $nodeType->setThirdPartySetting('server_general', 'nids_with_attached_js', $nids);
  $nodeType->save();
}
